### ISSUE TITLE
Snapping options function not working in 2.14

### ISSUE THREAD

**Issue by rjwillson** [enricofer/pickLayer#2]
first of all, this is one of the best plugins available for QGIS in terms of increasing speed of work

I'm not sure if the Snapping options worked in 2.12 but in 2.14 when one picks the layer to turn on snapping (as shown below) nothing happens and snapping is not activated for selected layer - at least not in my project.  

the ability of the plugin to do this is very helpful when one has a long list of layers in a project

![2016-04-26_cr](https://cloud.githubusercontent.com/assets/11098144/14836026/2f620d60-0bdb-11e6-9d86-60226907f93f.png)

![2016-04-26 1 _cr](https://cloud.githubusercontent.com/assets/11098144/14836076/969be294-0bdb-11e6-81fa-924f459f02f8.png)

**Comment by enricofer** [comment]
issue fixed: https://github.com/enricofer/pickLayer/commit/f26501a81608f5731f552db2cc5d5d528e48433b
I will upload it to repository soon. In the meanwhile download it from master.
Thanks for submission

**Comment by rjwillson** [comment]
works beautifully now and I see you added "avoid intersections" which is really great to speed up turning that feature on and off 

thanks so much!
